/**:
  ros__parameters:
    pointcloud_sensor:
      base_setup:
        tf_name: "base_sensorring"
        auto_discover: false
        enforce_topology: false
        repair_errors: true
        timeout_ms: 1000
      publishers:
        depth_individual: false
        depth_combined: true
        depth_raw: false
      htpa32_config:
        enable: false
        auto_min_max: false
        use_eeprom_file: true
        use_calibration_file: true
        eeprom_file_dir: ".eduart/sensorring/eeprom"
        calibration_file_dir: ".eduart/sensorring/calibration"
        scale_t_min_deg: 20.0
        scale_t_max_deg: 35.0
        max_rate_hz: 5.0
      vl53l8cx_config:
        enable: true
        max_rate_hz: 15.0
      tmf8829_config:
        enable: true
        resolution_mode: 3 # 0=8x8, 1=8x8LR, 2=8x8HA, 3=16x16, 4=16x16HA, 5=32x32, 6=32x32HA, 7=48x32, 8=48x32HA
        k_iterations: 0
        max_rate_hz: 15.0
      led_config:
        initial_mode: 10 # Off=0, Dimmed=1, HighBeam=2, FlashAll=3, FlashLeft=4, FlashRight=5, Pulsation=6, Rotation=7, Running=8, MapDistance=9, FixedColor=10, PulsationColor=11
        initial_color: [64, 64, 64]
      topology:
        nr_of_interfaces: 1
        interfaces:
          interface_0:
            interface_type: "socketcan"
            interface_name: "eduart-can1"
            enable_brs: false
            data_baudrate: 3333333
            sample_point: 0.95
            nr_of_boards: 8
            boards:
              board_0:
                expected_devices: ["any_depth"]
                orientation: "left"
                rotation: [-90.0, -19.0, -100.0]
                translation: [0.0925, -0.031, 0.05]
              board_1:
                expected_devices: ["any_depth"]
                orientation: "left"
                rotation: [0.0, 90.0, -80.0]
                translation: [0.025, -0.0725, 0.07]
              board_2:
                expected_devices: ["any_depth"]
                orientation: "left"
                rotation: [0.0, 90.0, -100.0]
                translation: [-0.025, -0.0725, 0.07]
              board_3:
                expected_devices: ["any_depth"]
                orientation: "left"
                rotation: [0.0, -90.0, 20.0]
                translation: [-0.0925, -0.0325, 0.054]
              board_4:
                expected_devices: ["any_depth"]
                orientation: "right"
                rotation: [0.0, 90.0, 160.0]
                translation: [-0.0925, 0.0325, 0.054]
              board_5:
                expected_devices: ["any_depth"]
                orientation: "right"
                rotation: [-90.0, 0.0, 10.0]
                translation: [-0.0275, 0.0725, 0.067]
              board_6:
                expected_devices: ["any_depth"]
                orientation: "right"
                rotation: [-90.0, 0.0, -10.0]
                translation: [0.0275, 0.0725, 0.067]
              board_7:
                expected_devices: ["any_depth"]
                orientation: "right"
                rotation: [90.0, -19.0, 100.0]
                translation: [0.0925, 0.031, 0.05]
