/**:
  ros__parameters:
    pointcloud_sensor:
      base_setup:
        tf_name: "base_sensorring"
        print_topology: false
        frequency_tof_hz: 0.0 # max frequency ~ 13.6...14.1 Hz (0.0 -> free running)
        frequency_thermal_hz: 5.0 # max frequency ~ 5.0 Hz
        timeout_ms: 1000
      thermal_config:
        auto_min_max: false
        use_eeprom_file: true
        use_calibration_file: true
        eeprom_file_dir: ".eduart/sensorring/eeprom"
        calibration_file_dir: ".eduart/sensorring/calibration"
        scale_t_min_deg: 20.0
        scale_t_max_deg: 35.0
      topology:
        nr_of_interfaces: 1
        can_interfaces:
          can_interface_0:
            interface_type: "socketcan"
            interface_name: "eduart-can1"
            orientation: "left"
            nr_of_sensors: 8
            sensors:
              sensor_0:
                enable_tof: true
                enable_thermal: false
                enable_light : true
                rotation: [-90.0, -19.0, -100.0]
                translation: [0.0925, -0.031, 0.05]
              sensor_1:
                enable_tof: true
                enable_thermal: false
                enable_light : true
                rotation: [0.0, 90.0, -80.0]
                translation: [0.025, -0.0725, 0.07]
              sensor_2:
                enable_tof: true
                enable_thermal: false
                enable_light : true
                rotation: [0.0, 90.0, -100.0]
                translation: [-0.025, -0.0725, 0.07]
              sensor_3:
                enable_tof: true
                enable_thermal: false
                enable_light : true
                rotation: [0.0, -90.0, 20.0]
                translation: [-0.0925, -0.0325, 0.054]
              sensor_4:
                enable_tof: true
                enable_thermal: false
                enable_light : true
                rotation: [0.0, 90.0, 160.0]
                translation: [-0.0925, 0.0325, 0.054]
              sensor_5:
                enable_tof: true
                enable_thermal: false
                enable_light : true
                rotation: [-90.0, 0.0, 10.0]
                translation: [-0.0275, 0.0725, 0.067]
              sensor_6:
                enable_tof: true
                enable_thermal: false
                enable_light : true
                rotation: [-90.0, 0.0, -10.0]
                translation: [0.0275, 0.0725, 0.067]
              sensor_7:
                enable_tof: true
                enable_thermal: false
                enable_light : true
                rotation: [90.0, -19.0, 100.0]
                translation: [0.0925, 0.031, 0.05]
