services:
    sensor_ring:
        build:
          context: ../../../../
          dockerfile: ./ros2_ws/src/sensorring_ros2/docker/Dockerfile
        container_name: sensorring_ros2-0.1.0
        user: user
        restart: always
        privileged: true
        ipc: host
        pid: host
        mem_limit: 300mb
        environment:
            - EDU_ROBOT_NAMESPACE=${EDU_ROBOT_NAMESPACE}
            - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION}
            - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
        network_mode: "host"
        command: bash -c 'cd /home/user/ros/launch_content; ros2 launch sensorring_ros2.launch.py'
        # command: /bin/bash
        # stdin_open: true
        volumes:
            - './launch_content:/home/user/ros/launch_content'
            - './../calibration:/home/user/ros/calibration'
        devices:
            - '/dev:/dev'