services:
    edu_sensorring_ros2:
        build:
          context: ../../
          dockerfile: ./edu_sensorring_ros2/docker/Dockerfile
        image: sensorring
        container_name: edu_sensorring_ros2-1.0.0
        user: user
        restart: always
        privileged: true
        ipc: host
        pid: host
        mem_limit: 300mb
        environment:
            - EDU_ROBOT_NAMESPACE=${EDU_ROBOT_NAMESPACE}
            - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION}
            - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
        network_mode: "host"
        command: bash -c 'cd /home/user/ros/launch_content; ros2 launch edu_sensorring_ros2.launch.py'
        # command: /bin/bash
        # stdin_open: true
        volumes:
            - './launch_content:/home/user/ros/launch_content'
            - '~/.eduart/sensorring/:/home/user/.eduart/sensorring/'
        #devices:
        #    - '/dev:/dev'